"""initial schema

Revision ID: 835b411f101a
Revises: 
Create Date: 2026-09-06 12:54:39.507366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '835b411f101a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Phải chạy TRƯỚC bất kỳ bảng nào dùng cột `vector` (document_chunks,
    # memory_events) — kiểu dữ liệu này do extension cung cấp, không có sẵn
    # trong Postgres gốc. Autogenerate KHÔNG tự phát hiện/thêm dòng này (nó
    # chỉ so sánh Table/Column trong models.py, không biết gì về extension) —
    # phải tự thêm tay ở mọi lần deploy lên DB mới.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('learning_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_level', sa.String(), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_user_id'), 'topics', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('position_ref', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.create_table('document_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position_ref', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_topics_document_id'), 'document_topics', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_topics_user_id'), 'document_topics', ['user_id'], unique=False)
    op.create_table('flashcard_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_sets_document_id'), 'flashcard_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_flashcard_sets_user_id'), 'flashcard_sets', ['user_id'], unique=False)
    op.create_table('mastery_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_mastery_scores_user_topic')
    )
    op.create_index(op.f('ix_mastery_scores_topic_id'), 'mastery_scores', ['topic_id'], unique=False)
    op.create_index(op.f('ix_mastery_scores_user_id'), 'mastery_scores', ['user_id'], unique=False)
    op.create_table('memory_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_events_topic_id'), 'memory_events', ['topic_id'], unique=False)
    op.create_index(op.f('ix_memory_events_user_id'), 'memory_events', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cited_sources', sa.Text(), nullable=True),
    sa.Column('is_grounded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_document_id'), 'quizzes', ['document_id'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('flashcard_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flashcard_set_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('source_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_set_id'], ['flashcard_sets.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_items_flashcard_set_id'), 'flashcard_items', ['flashcard_set_id'], unique=False)
    op.create_index(op.f('ix_flashcard_items_topic_id'), 'flashcard_items', ['topic_id'], unique=False)
    op.create_table('quiz_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('source_position', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_items_quiz_id'), 'quiz_items', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_items_topic_id'), 'quiz_items', ['topic_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('quiz_item_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_item_id'], ['quiz_items.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_quiz_item_id'), 'attempts', ['quiz_item_id'], unique=False)
    op.create_index(op.f('ix_attempts_topic_id'), 'attempts', ['topic_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('flashcard_item_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_item_id'], ['flashcard_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_flashcard_item_id'), 'flashcard_reviews', ['flashcard_item_id'], unique=False)
    op.create_index(op.f('ix_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Index HÀM (functional index) cho nhánh từ khoá của hybrid search
    # (app/vectorstore/pgvector_store.py) — thay cho rank_bm25 tính lại toàn
    # bộ mỗi lần gọi trước đây. 'simple' (không stemming tiếng Việt, chỉ
    # tách từ/hạ chữ thường) thay vì 'english' — 'english' sẽ áp stemmer
    # tiếng Anh sai ngữ cảnh lên nội dung tiếng Việt. SQLAlchemy chưa có API
    # bậc cao cho index hàm nên viết SQL trực tiếp.
    op.execute(
        "CREATE INDEX ix_document_chunks_text_fts ON document_chunks "
        "USING gin (to_tsvector('simple', text))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_text_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcard_reviews_user_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_flashcard_item_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_topic_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_quiz_item_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_quiz_items_topic_id'), table_name='quiz_items')
    op.drop_index(op.f('ix_quiz_items_quiz_id'), table_name='quiz_items')
    op.drop_table('quiz_items')
    op.drop_index(op.f('ix_flashcard_items_topic_id'), table_name='flashcard_items')
    op.drop_index(op.f('ix_flashcard_items_flashcard_set_id'), table_name='flashcard_items')
    op.drop_table('flashcard_items')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_document_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memory_events_user_id'), table_name='memory_events')
    op.drop_index(op.f('ix_memory_events_topic_id'), table_name='memory_events')
    op.drop_table('memory_events')
    op.drop_index(op.f('ix_mastery_scores_user_id'), table_name='mastery_scores')
    op.drop_index(op.f('ix_mastery_scores_topic_id'), table_name='mastery_scores')
    op.drop_table('mastery_scores')
    op.drop_index(op.f('ix_flashcard_sets_user_id'), table_name='flashcard_sets')
    op.drop_index(op.f('ix_flashcard_sets_document_id'), table_name='flashcard_sets')
    op.drop_table('flashcard_sets')
    op.drop_index(op.f('ix_document_topics_user_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_document_id'), table_name='document_topics')
    op.drop_table('document_topics')
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_topics_user_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('learning_profiles')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
